config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='post')),
    path('contact/', include('contact.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from  django.urls import path
from .views import contact_view

app_name = 'posts'

urlpatterns = [
    path('', contact_view, name='contact')
]

posts/urls.py
from django.urls import path
from .views import home_view, single_view, about_view, fashion_view, travel_view

app_name = 'post'  # {% url 'app_name:urlname' %}

urlpatterns = [
    path('', home_view, name='home'),
    path('single/<slug:slug>/', single_view, name='single'),
    path('about/', about_view, name='about'),
    path('fashion/', fashion_view, name='fashion'),
    path('travel/', travel_view, name='travel'),
]

contact/models.py
from django.db import models


class GetInTouch(models.Model):
    name = models.CharField(max_length=221)
    email = models.EmailField()
    subject = models.CharField(max_length=221)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Subscribe(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

posts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

TYPE = (
    (0, 'FASHION'),
    (1, 'TRAVEL'),
)


class Category(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title


class Tag(models.Model):
    tag = models.CharField(max_length=221)

    def __str__(self):
        return self.tag


# get_<field_name>_display
def post_image_path(instance, filename):
    return 'posts/%s/%s' % (instance.get_type_display(), filename)


class Post(models.Model):
    title = models.CharField(max_length=221)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    type = models.IntegerField(choices=TYPE)
    slug = models.SlugField(blank=True)
    image = models.ImageField(upload_to=post_image_path)
    content = models.TextField()
    tags = models.ManyToManyField(Tag, blank=True)
    created_at = models.DateField()

    def __str__(self):
        return self.title

    def post_comments_count(self):
        return self.comment_set.count()


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    posts = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=221)
    avatar = models.ImageField(upload_to='comments', null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.author.username

contact/forms.py
from django import forms
from .models import GetInTouch, Subscribe


class CreateGetInTouchForm(forms.ModelForm):
    class Meta:
        model = GetInTouch
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CreateGetInTouchForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name.capitalize()


class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscribe
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(SubscribeForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name.capitalize()

posts/forms.py
from django import forms
from .models import Comment


class CreateCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        exclude = ('author',)

    def __init__(self, *args, **kwargs):
        super(CreateCommentForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            # field.widget.attrs['placeholder'] = field_name

contact/views.py
from django.shortcuts import render, redirect
from .forms import CreateGetInTouchForm
from .models import GetInTouch, Subscribe


def contact_view(request):
    form = CreateGetInTouchForm(request.POST or None)
    obj = GetInTouch.objects.order_by('-id')[:2]
    if form.is_valid():
        comment = form.save(commit=False)
        comment.obj = obj
        comment.save()
        return redirect('.')
    ctx = {
        'form': form,
        'objects': obj
    }
    return render(request, 'contact/contact.html', ctx)

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Tag, Comment, Category
from .forms import CreateCommentForm
from contact.models import Subscribe
from django.core.paginator import Paginator


def home_view(request):
    objects = Post.objects.order_by('-id')
    paginator = Paginator(objects, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    comments = Comment.objects.all()
    last_3_posts = Post.objects.order_by('-id')[:3]
    tags = Tag.objects.all()
    categories = Category.objects.all()
    q = request.GET.get('search')
    cat = request.GET.get('cat')
    tag = request.GET.get('tag')
    sbb = request.POST.get('sbb')

    if q:
        objects = objects.filter(title__icontains=q)
    if cat:
        objects = objects.filter(category__title__exact=cat)
    if tag:
        objects = objects.filter(tags__tag__exact=tag)

    if request.method == 'POST':
        Subscribe.objects.create(email=sbb)
    dates = list()
    [('yanvar', 2020), ('aprel', 2021)]
    for i in objects:
        month = i.created_at.strftime("%B")
        year = i.created_at.strftime("%Y")
        mydate = i.created_at.strftime("%B %Y")
        if mydate not in dates:
            dates.append((f'{month}', year))
        print(dates)
    month = request.GET.get('month')
    year = request.GET.get('year')

    if month and year:
        objects = objects.filter(created_at__year=year)
    context = {
        'objects': objects,
        'page_obj': page_obj,
        'comments': comments,
        'last_3_posts': last_3_posts,
        'tags': tags,
        'categories': categories,
        "dates": dates
    }
    return render(request, 'posts/index.html', context)


def single_view(request, slug):
    objects = get_object_or_404(Post, slug=slug)
    posts = Post.objects.order_by('-id')
    categories = Category.objects.all()
    tags = Tag.objects.all()
    last_3_post = Post.objects.order_by('-id')[:3]
    comments = Comment.objects.filter(posts__slug__exact=slug).order_by('-id')
    form = CreateCommentForm(request.POST or None, request.FILES or None, instance=objects)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.objects = objects
        comment.author = request.user
        comment.save()
        return redirect(f'/single/{objects.slug}#comments')

    email = request.POST.get('subs')
    if email:
        Subscribe.objects.create(email)

    ctx = {
        'tags': tags,
        'form': form,
        'posts': posts,
        'objects': objects,
        'comments': comments,
        'categories': categories,
        'last_3_posts': last_3_post,

    }
    return render(request, 'posts/single.html', ctx)


def about_view(request):
    return render(request, 'posts/about.html')


def fashion_view(request):
    post = Post.objects.filter(type=0).order_by('-id')
    ctx = {
        'objects': post
    }
    return render(request, 'posts/fashion.html', ctx)


def travel_view(request):
    post = Post.objects.filter(type=1).order_by('-id')
    tags = Tag.objects.all()
    categories = Category.objects.all()
    last_3_post = Post.objects.order_by('-id')[:3]
    email = request.POST.get('subs')
    paginator = Paginator(post, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    if email:
        Subscribe.objects.create(email=email)
    ctx = {
        'objects': page_obj,
        'tags': tags,
        'categories': categories,
        'last_3_posts': last_3_post
    }
    return render(request, 'posts/travel.html', ctx)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AnderaProject</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface&amp;display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script nonce="d3e66675-56be-4b18-8c29-526bbfe8ae41">(function (w, d) {
        !function (a, e, t, r) {
            a.zarazData = a.zarazData || {}, a.zarazData.executed = [], a.zaraz = {deferred: []}, a.zaraz.q = [], a.zaraz._f = function (e) {
                return function () {
                    var t = Array.prototype.slice.call(arguments);
                    a.zaraz.q.push({m: e, a: t})
                }
            };
            for (const e of ["track", "set", "ecommerce", "debug"]) a.zaraz[e] = a.zaraz._f(e);
            a.addEventListener("DOMContentLoaded", (() => {
                var t = e.getElementsByTagName(r)[0], z = e.createElement(r), n = e.getElementsByTagName("title")[0];
                for (n && (a.zarazData.t = e.getElementsByTagName("title")[0].text), a.zarazData.w = a.screen.width, a.zarazData.h = a.screen.height, a.zarazData.j = a.innerHeight, a.zarazData.e = a.innerWidth, a.zarazData.l = a.location.href, a.zarazData.r = e.referrer, a.zarazData.k = a.screen.colorDepth, a.zarazData.n = e.characterSet, a.zarazData.o = (new Date).getTimezoneOffset(), a.zarazData.q = []; a.zaraz.q.length;) {
                    const e = a.zaraz.q.shift();
                    a.zarazData.q.push(e)
                }
                z.defer = !0, z.referrerPolicy = "origin", z.src = "/cdn-cgi/zaraz/s.js?z=" + btoa(encodeURIComponent(JSON.stringify(a.zarazData))), t.parentNode.insertBefore(z, t)
            }))
        }(w, d, 0, "script");
    })(window, document);</script>
</head>
<body>

<div id="colorlib-page">
    <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
    {% include 'sidebar.html' %}

    {% block content %}

    {% endblock %}

</div>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js+popper.min.js+bootstrap.min.js.pagespeed.jc.ufA-InWYhU.js' %}"></script>
<script>eval(mod_pagespeed_j9z0BOW3Xo);</script>
<script>eval(mod_pagespeed_Sv59xs6XfY);</script>
<script>eval(mod_pagespeed_6hivBMilT4);</script>
<script src="{% static 'js/jquery.easing.1.3.js+jquery.waypoints.min.js+jquery.stellar.min.js+owl.carousel.min.js.pagespeed.jc.7Uf8nwPPt3.js' %}"></script>
<script>eval(mod_pagespeed_a9in6ca9LP);</script>
<script>eval(mod_pagespeed_E5Rl_eUdra);</script>
<script>eval(mod_pagespeed_J7fR9gg3IV);</script>
<script>eval(mod_pagespeed_JGC9XV$UWo);</script>
<script src="{% static 'js/jquery.magnific-popup.min.js+aos.js+jquery.animateNumber.min.js+scrollax.min.js+google-map.js+main.js.pagespeed.jc.noK85cOv9x.js' %}"></script>
<script>eval(mod_pagespeed_9FDixMCPbL);</script>
<script>eval(mod_pagespeed_cWDp1F0K9O);</script>
<script>eval(mod_pagespeed_tBed9FYmsP);</script>
<script>eval(mod_pagespeed_xipmmYMCNr);</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;sensor=false"></script>
<script>eval(mod_pagespeed_YuUFcjXVeT);</script>
<script>eval(mod_pagespeed_6pY$MsZg3C);</script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
</script>
<script defer
        src="https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194"
        integrity="sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw=="
        data-cf-beacon='{"rayId":"702f915cae41fe54","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2021.12.0","si":100}'
        crossorigin="anonymous"></script>


</body>
</html>

templates/contact/contact.html
{% extends 'base.html' %}
{% block content %}
    <div id="colorlib-main">
        <section class="ftco-section contact-section px-md-4">
            <div class="container">
                <div class="row d-flex mb-5 contact-info">
                    <div class="col-md-12 mb-4">
                        <h2 class="h3">Contact Information</h2>
                    </div>
                    <div class="w-100"></div>
                    <div class="col-lg-6 col-xl-3 d-flex mb-4">
                        <div class="info bg-light p-4">
                            <p><span>Address:</span> 198 West 21th Street, Suite 721 New York NY 10016</p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xl-3 d-flex mb-4">
                        <div class="info bg-light p-4">
                            <p><span>Phone:</span> <a href="tel://1234567920">+ 1235 2355 98</a></p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xl-3 d-flex mb-4">
                        <div class="info bg-light p-4">
                            <p><span>Email:</span> <a
                                    href="https://preview.colorlib.com/cdn-cgi/l/email-protection#ec85828a83ac9583999e9f859889c28f8381"><span
                                    class="__cf_email__" data-cfemail="a5cccbc3cae5dccad0d7d6ccd1c08bc6cac8">[email&#160;protected]</span></a>
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xl-3 d-flex mb-4">
                        <div class="info bg-light p-4">
                            <p><span>Website</span> <a href="#">yoursite.com</a></p>
                        </div>
                    </div>
                </div>
                <div class="row block-9">
                    <div class="col-lg-6 d-flex">
                        <form method="post" class="bg-light p-5 contact-form">
                            {% csrf_token %}
                            <div class="form-group">
{#                                <input type="text" class="form-control" placeholder="Your Name">#}
                                {{ form.name }}
                            </div>
                            <div class="form-group">
{#                                <input type="text" class="form-control" placeholder="Your Email">#}
                                {{ form.email }}
                            </div>
                            <div class="form-group">
{#                                <input type="text" class="form-control" placeholder="Subject">#}
                                {{ form.subject }}
                            </div>
                            <div class="form-group">
{#                                <textarea name="" id="" cols="30" rows="7" class="form-control" placeholder="Message"></textarea>#}
                                {{ form.message }}
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
                            </div>
                        </form>
                    </div>
                    <div class="col-lg-6 d-flex">
                        <div id="map" class="bg-light"></div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                    stroke="#F96D00"/>
        </svg>
    </div>
{% endblock %}

templates/pagination.html
<div class="row">
    <div class="col text-center text-md-left">
        <div class="block-27">
            <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&gt;</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="pagination">
    <span class="step-links">
        {% if objects.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ objects.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ objects.number }} of {{ objects.paginator.num_pages }}.
        </span>

        {% if objects.has_next %}
            <a href="?page={{ objects.next_page_number }}">next</a>
            <a href="?page={{ objects.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

templates/posts/fashion.html
{% extends 'base.html' %}

{% block content %}
    <div id="colorlib-main">
        <section class="ftco-section">
            <div class="container">
                <div class="row px-md-4">
                    <div class="col-md-12">
                        {% for object in objects %}
                        <div class="blog-entry ftco-animate d-md-flex">
                            <a href="{% url 'post:single' slug=object.slug %}" class="img img-2"
                               style="background-image:url({{ object.image.url }})"></a>
                            <div class="text text-2 pl-md-4">
                                <h3 class="mb-2"><a href="{% url 'post:single' slug=object.slug %}">{{ object.title }}</a></h3>
                                <div class="meta-wrap">
                                    <p class="meta">
                                        <span><i class="icon-calendar mr-2"></i>{{ object.created_at }}</span>
                                        <span><a href="{% url 'post:single' slug=object.slug %}"><i class="icon-folder-o mr-2"></i>{{ object.category }}</a></span>
                                        <span><i class="icon-comment2 mr-2"></i>{{ object.comment_set.count }} Comment</span>
                                    </p>
                                </div>
                                <p class="mb-4">{{ object.content|slice:230 }}</p>
                                <p><a href="{% url 'post:single' slug=object.slug %}" class="btn-custom">Read More <span class="ion-ios-arrow-forward"></span></a>
                                </p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                {% include 'pagination.html' %}
            </div>
        </section>
    </div>

    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                    stroke="#F96D00"/>
        </svg>
    </div>

{% endblock %}

templates/posts/index.html
{% extends 'base.html' %}

{% block content %}

    <div id="colorlib-main">
        <section class="ftco-section ftco-no-pt ftco-no-pb">
            <div class="container">
                <div class="row d-flex">
                    <div class="col-xl-8 py-5 px-md-5">
                        <div class="row pt-md-4">
                            {% for object in objects %}
                            <div class="col-md-12">
                                <div class="blog-entry ftco-animate d-md-flex">
                                    <a href="{% url 'post:single' slug=object.slug %}" class="img img-2"
                                       style="background-image: url({{ object.image.url }});"></a>
                                    <div class="text text-2 pl-md-4">
                                        <h3 class="mb-2"><a href="{% url 'post:single' slug=object.slug %}">{{ object.title }}</a></h3>
                                        <div class="meta-wrap">
                                            <p class="meta">
                                                <span><i class="icon-calendar mr-2"></i>{{ object.created_at }}</span>
                                                <span><a href="{% url 'post:single' slug=object.slug %}"><i class="icon-folder-o mr-2"></i>{{ object.category }}</a></span>
                                                <span><i class="icon-comment2 mr-2"></i>{{ object.post_comments_count  }} Comments</span>
                                            </p>
                                        </div>
                                        <p class="mb-4">{{ object.content|slice:100 }}</p>
                                        <p><ul class="tagcloud">
{#                                                    {% for tag in object.tags.all %}#}
{#                                                        <a href="?tag={{ tag.tags }}" class="tag-cloud-link">{{ tag.tag }}</a>#}
{#                                                    {% endfor %}#}
                                                </ul></p>
                                        <p><a href="{% url 'post:single' slug=object.slug %}" class="btn-custom">Read More <span
                                                class="ion-ios-arrow-forward"></span></a></p>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        {% include 'pagination.html' %}
                    </div>
                    {% include 'rsite.html' with objects=objects dates=dates categories=categories tags=tags last_3_posts=last_3_posts %}
                </div>
            </div>
        </section>
    </div>
    </div>

    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                    stroke="#F96D00"/>
        </svg>
    </div>
{% endblock %}

templates/posts/travel.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div id="colorlib-main">
        <section class="ftco-section ftco-no-pt ftco-no-pb">
            <div class="container">
                <div class="row d-flex">
                    <div class="col-xl-8 px-md-5 py-5">
                        <div class="row pt-md-4">
                            <div class="col-md-12">
                                {% for object in objects %}
                                    <div class="blog-entry-2 ftco-animate">
                                        <a href="{% url 'post:single' slug=object.slug %}" class="img"
                                           style="background-image:url({{ object.image.url }})"></a>
                                        <div class="text pt-4">
                                            <h3 class="mb-4"><a
                                                    href="{% url 'post:single' slug=object.slug %}">{{ object.title }}</a>
                                            </h3>
                                            <p class="mb-4">{{ object.content|slice:250 }}...</p>
                                            <div class="author mb-4 d-flex align-items-center">
                                                <a href="{% url 'post:single' slug=object.slug %}" class="img"
                                                   style="background-image: url({% static 'images/person_1.jpg' %});"></a>
                                                <div class="ml-3 info">
                                                    <span>Written by</span>
                                                    <h3><a href="{% url 'post:single' slug=object.slug %}">Dave Lewis</a>, <span>{{ object.created_at }}</span></h3>
                                                </div>
                                            </div>
                                            <div class="meta-wrap d-md-flex align-items-center">
                                                <div class="half order-md-last text-md-right">
                                                    <p class="meta">
                                                        <span><i class="icon-heart"></i>3</span>
                                                        <span><i class="icon-eye"></i>120</span>
                                                        <span><i class="icon-comment"></i>{{ object.comment_set.count }}</span>
                                                    </p>
                                                </div>
                                                <div class="half">
                                                    <p><a href="{% url 'post:single' slug=object.slug %}" class="btn btn-primary p-3 px-xl-4 py-xl-3">Continue
                                                        Reading</a></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                        {% include 'pagination.html' %}
                    </div>
                    {% include 'rsite.html' %}
                </div>
            </div>
        </section>
    </div>

    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                    stroke="#F96D00"/>
        </svg>
    </div>

{% endblock %}

templates/rsite.html
{% load static %}
<div class="col-lg-4 sidebar ftco-animate bg-light pt-5">
    <div class="sidebar-box pt-md-4">
        <form action="/" class="search-form">
            <div class="form-group">
                <span class="icon icon-search"></span>
                <input type="search" name="search" class="form-control" placeholder="Type a keyword and hit enter">
            </div>
        </form>
    </div>
    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Categories</h3>
        <ul class="categories">
            {% for category in categories %}
            <li><a href="/?cat={{ category }}">{{ category }} <span>{{ category.post_set.count }}</span></a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Last Articles</h3>
        {% for last_3_post in last_3_posts %}
        <div class="block-21 mb-4 d-flex">
            <a class="blog-img mr-4" href="#"
               style="background-image:url({{ last_3_post.image.url }})"></a>
            <div class="text">
                <h3 class="heading"><a href="#">{{ last_3_post.title }}</a>
                </h3>
                <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span>{{ last_3_post.created_at }}</a></div>
                    <div><a href="#"><span class="icon-person"></span>{{ last_3_post.category }}</a></div>
                    <div><a href="#"><span class="icon-chat"></span>{{ last_3_post.comment_set.count }}</a></div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Tag Cloud</h3>
        <ul class="tagcloud">
            {% for tag in tags %}
            <a href="/?tag={{ tag }}" class="tag-cloud-link">{{ tag }}</a>
            {% endfor %}
        </ul>
    </div>
    <div class="sidebar-box subs-wrap img"
         style="background-image:url({% static 'images/xbg_1.jpg.pagespeed.ic.yyDakF8d8Y.jpg' %})">
        <div class="overlay"></div>
        <h3 class="mb-4 sidebar-heading">Newsletter</h3>
        <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia</p>
        <form method="post" class="subscribe-form">
            {% csrf_token %}
            <div class="form-group">
                <input type="email" name="subs" class="form-control" placeholder="Email Address">
                <input type="submit" value="Subscribe" class="mt-2 btn btn-white submit">
            </div>
        </form>
    </div>
    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Archives</h3>
        <ul class="categories">
            {% for date in dates %}
                <li><a href="?month={{ date.0 }}&year={{ date.1 }}">{{ date.0 }} - {{ date.1 }} <span></span></a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Paragraph</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem
            necessitatibus voluptate quod mollitia delectus aut.</p>
    </div>
</div>